spring:
  datasource:
    url: jdbc:mysql://localhost:3306/conecta
    username: conecta
    password: conecta
  jpa:
    hibernate:
      format-sql: true
    show-sql: true
  cloud:
    gcp:
      firestore:
        projectId: conecta-care-e77c0
      credentials:
        location: file:care-contact/src/main/resources/credentials-firebase.json

server:
  servlet:
    context-path: /care-contact