-- genero

INSERT INTO genero (id, tipo, descricao) VALUES(1, 'M', 'MASCULINO');
INSERT INTO genero (id, tipo, descricao) VALUES(2, 'F', 'FEMININO');

-- especialidade

INSERT INTO especialidade (id, nome) VALUES(1, 'Biologia');
INSERT INTO especialidade (id, nome) VALUES(2, 'Biomedicina');
INSERT INTO especialidade (id, nome) VALUES(3, 'Educação Física');
INSERT INTO especialidade (id, nome) VALUES(4, 'Enfermagem');
INSERT INTO especialidade (id, nome) VALUES(5, 'Farmácia');
INSERT INTO especialidade (id, nome) VALUES(6, 'Fisioterapia e Terapia');
INSERT INTO especialidade (id, nome) VALUES(7, 'Fonoaudiologia');
INSERT INTO especialidade (id, nome) VALUES(8, 'Medicina');
INSERT INTO especialidade (id, nome) VALUES(9, 'Medicina Veterinária');
INSERT INTO especialidade (id, nome) VALUES(10, 'Nutrição');
INSERT INTO especialidade (id, nome) VALUES(11, 'Odontologia');
INSERT INTO especialidade (id, nome) VALUES(12, 'Psicologia');
INSERT INTO especialidade (id, nome) VALUES(13, 'Serviço Social');

-- banco

INSERT INTO banco (id, codigo, descricao) VALUES(1, '001', 'Banco do Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(2, '341', 'Banco Itaú S.A');
INSERT INTO banco (id, codigo, descricao) VALUES(3, '033', 'Banco Santander (Brasil) S.A');
INSERT INTO banco (id, codigo, descricao) VALUES(4, '356', 'Banco Real S.A. (antigo)');
INSERT INTO banco (id, codigo, descricao) VALUES(5, '652', 'Itaú Unibanco Holding S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(6, '237', 'Banco Bradesco S.A');
INSERT INTO banco (id, codigo, descricao) VALUES(7, '745', 'Banco Citibank S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(8, '399', 'HSBC Bank Brasil S.A. – Banco Múltiplo');
INSERT INTO banco (id, codigo, descricao) VALUES(9, '104', 'Caixa Econômica Federal');
INSERT INTO banco (id, codigo, descricao) VALUES(10, '389', 'Banco Mercantil do Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(11, '453', 'Banco Rural S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(12, '422', 'Banco Safra S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(13, '633', 'Banco Rendimento S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(14, '246', 'Banco ABC Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(15, '641', 'Banco Alvorada S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(16, '025', 'Banco Alfa S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(17, '029', 'Banco Banerj S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(18, '038', 'Banco Banestado S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(19, '000', 'Banco Bankpar S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(20, '740', 'Banco Barclays S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(21, '107', 'Banco BBM S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(22, '031', 'Banco Beg S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(23, '096', 'Banco BM&F de Serviços de Liquidação e Custódia S.A');
INSERT INTO banco (id, codigo, descricao) VALUES(24, '318', 'Banco BMG S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(25, '752', 'Banco BNP Paribas Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(26, '248', 'Banco Boavista Interatlântico S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(27, '036', 'Banco Bradesco BBI S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(28, '204', 'Banco Bradesco Cartões S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(29, '225', 'Banco Brascan S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(30, '044', 'Banco BVA S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(31, '263', 'Banco Cacique S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(32, '473', 'Banco Caixa Geral – Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(33, '222', 'Banco Calyon Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(34, '040', 'Banco Cargill S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(35, 'M08', 'Banco Citicard S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(36, 'M19', 'Banco CNH Capital S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(37, '215', 'Banco Comercial e de Investimento Sudameris S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(38, '756', 'Banco Cooperativo do Brasil S.A. – BANCOOB');
INSERT INTO banco (id, codigo, descricao) VALUES(39, '748', 'Banco Cooperativo Sicredi S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(40, '505', 'Banco Credit Suisse (Brasil) S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(41, '229', 'Banco Cruzeiro do Sul S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(42, '003', 'Banco da Amazônia S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(43, '083-3', 'Banco da China Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(44, '707', 'Banco Daycoval S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(45, 'M06', 'Banco de Lage Landen Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(46, '024', 'Banco de Pernambuco S.A. – BANDEPE');
INSERT INTO banco (id, codigo, descricao) VALUES(47, '456', 'Banco de Tokyo-Mitsubishi UFJ Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(48, '214', 'Banco Dibens S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(49, '047', 'Banco do Estado de Sergipe S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(50, '037', 'Banco do Estado do Pará S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(51, '041', 'Banco do Estado do Rio Grande do Sul S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(52, '004', 'Banco do Nordeste do Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(53, '265', 'Banco Fator S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(54, 'M03', 'Banco Fiat S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(55, '224', 'Banco Fibra S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(56, '626', 'Banco Ficsa S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(57, '394', 'Banco Finasa BMC S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(58, 'M18', 'Banco Ford S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(59, '233', 'Banco GE Capital S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(60, '734', 'Banco Gerdau S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(61, 'M07', 'Banco GMAC S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(62, '612', 'Banco Guanabara S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(63, 'M22', 'Banco Honda S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(64, '063', 'Banco Ibi S.A. Banco Múltiplo');
INSERT INTO banco (id, codigo, descricao) VALUES(65, 'M11', 'Banco IBM S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(66, '604', 'Banco Industrial do Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(67, '320', 'Banco Industrial e Comercial S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(68, '653', 'Banco Indusval S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(69, '630', 'Banco Intercap S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(70, '249', 'Banco Investcred Unibanco S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(71, '184', 'Banco Itaú BBA S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(72, '479', 'Banco ItaúBank S.A');
INSERT INTO banco (id, codigo, descricao) VALUES(73, 'M09', 'Banco Itaucred Financiamentos S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(74, '376', 'Banco J. P. Morgan S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(75, '074', 'Banco J. Safra S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(76, '217', 'Banco John Deere S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(77, '065', 'Banco Lemon S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(78, '600', 'Banco Luso Brasileiro S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(79, '755', 'Banco Merrill Lynch de Investimentos S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(80, '746', 'Banco Modal S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(81, '151', 'Banco Nossa Caixa S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(82, '045', 'Banco Opportunity S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(83, '623', 'Banco Panamericano S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(84, '611', 'Banco Paulista S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(85, '643', 'Banco Pine S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(86, '638', 'Banco Prosper S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(87, '747', 'Banco Rabobank International Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(88, 'M16', 'Banco Rodobens S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(89, '072', 'Banco Rural Mais S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(90, '250', 'Banco Schahin S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(91, '749', 'Banco Simples S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(92, '366', 'Banco Société Générale Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(93, '637', 'Banco Sofisa S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(94, '464', 'Banco Sumitomo Mitsui Brasileiro S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(95, '082-5', 'Banco Topázio S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(96, 'M20', 'Banco Toyota do Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(97, '634', 'Banco Triângulo S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(98, '208', 'Banco UBS Pactual S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(99, 'M14', 'Banco Volkswagen S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(100, '655', 'Banco Votorantim S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(101, '610', 'Banco VR S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(102, '370', 'Banco WestLB do Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(103, '021', 'BANESTES S.A. Banco do Estado do Espírito Santo');
INSERT INTO banco (id, codigo, descricao) VALUES(104, '719', 'Banif-Banco Internacional do Funchal (Brasil)S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(105, '073', 'BB Banco Popular do Brasil S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(106, '078', 'BES Investimento do Brasil S.A.-Banco de Investimento');
INSERT INTO banco (id, codigo, descricao) VALUES(107, '069', 'BPN Brasil Banco Múltiplo S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(108, '070', 'BRB – Banco de Brasília S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(109, '477', 'Citibank N.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(110, '081-7', 'Concórdia Banco S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(111, '487', 'Deutsche Bank S.A. – Banco Alemão');
INSERT INTO banco (id, codigo, descricao) VALUES(112, '751', 'Dresdner Bank Brasil S.A. – Banco Múltiplo');
INSERT INTO banco (id, codigo, descricao) VALUES(113, '062', 'Hipercard Banco Múltiplo S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(114, '492', 'ING Bank N.V.');
INSERT INTO banco (id, codigo, descricao) VALUES(115, '488', 'JPMorgan Chase Bank');
INSERT INTO banco (id, codigo, descricao) VALUES(116, '409', 'UNIBANCO – União de Bancos Brasileiros S.A.');
INSERT INTO banco (id, codigo, descricao) VALUES(117, '230', 'Unicard Banco Múltiplo S.A.');

-- categoria_cnh

INSERT INTO categoria_cnh (id, sigla, descricao) VALUES(1, 'A', 'Veículo de duas ou três rodas, com ou sem carro lateral');
INSERT INTO categoria_cnh (id, sigla, descricao) VALUES(2, 'B', 'Veículo de passeio, com peso bruto total até 3500 Kg / lotação até 8 lugares');
INSERT INTO categoria_cnh (id, sigla, descricao) VALUES(3, 'C', 'Veículo utilizado em transporte de carga, peso bruto total acima de 3.500 kg');
INSERT INTO categoria_cnh (id, sigla, descricao) VALUES(4, 'D', 'Veículo utilizado no transporte de passageiros, lotação acima de 8 lugares');
INSERT INTO categoria_cnh (id, sigla, descricao) VALUES(5, 'E', 'Veículo que se enquadre nas categorias B, C ou D, tracionando unidade acoplada pesando 6.000 kg ou');

-- conselho

INSERT INTO conselho (id, sigla, descricao) VALUES(1, 'CRBio', 'Conselho Regional de Biologia');
INSERT INTO conselho (id, sigla, descricao) VALUES(2, 'CRBM', 'Conselho Regional de Biomedicina');
INSERT INTO conselho (id, sigla, descricao) VALUES(3, 'CREF', 'Conselho Regional de Educação Física');
INSERT INTO conselho (id, sigla, descricao) VALUES(4, 'Coren', 'Conselho Regional de Enfermagem');
INSERT INTO conselho (id, sigla, descricao) VALUES(5, 'CRF', 'Conselho Regional de Farmácia');
INSERT INTO conselho (id, sigla, descricao) VALUES(6, 'COFFITO', 'Conselho Regional de Enfermagem');
INSERT INTO conselho (id, sigla, descricao) VALUES(7, 'Crefono', 'Conselho Regional de Fonoaudiologia');
INSERT INTO conselho (id, sigla, descricao) VALUES(8, 'CRM', 'Conselho Regional de Medicina');
INSERT INTO conselho (id, sigla, descricao) VALUES(9, 'CRMV', 'Conselho Regional de Medicina Veterinária');
INSERT INTO conselho (id, sigla, descricao) VALUES(10, 'CRN', 'Conselho Regional de Nutricionistas');
INSERT INTO conselho (id, sigla, descricao) VALUES(11, 'CRO', 'Conselho Regional de Odontologia');
INSERT INTO conselho (id, sigla, descricao) VALUES(12, 'CRP', 'Conselho Regional de Psicologia');
INSERT INTO conselho (id, sigla, descricao) VALUES(13, 'Cress', 'Conselho Regional de Serviço Social');
INSERT INTO conselho (id, sigla, descricao) VALUES(14, 'Cuidador', 'Cuidador');

-- estado

INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(1, 11, 'RO', 'Rondônia', 'Região Norte');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(2, 12, 'AC', 'Acre', 'Região Norte');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(3, 13, 'AM', 'Amazonas', 'Região Norte');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(4, 14, 'RR', 'Roraima', 'Região Norte');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(5, 15, 'PA', 'Pará', 'Região Norte');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(6, 16, 'AP', 'Amapá', 'Região Norte');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(7, 17, 'TO', 'Tocantins', 'Região Norte');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(8, 21, 'MA', 'Maranhão', 'Região Nordeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(9, 22, 'PI', 'Piauí', 'Região Nordeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(10, 23, 'CE', 'Ceará', 'Região Nordeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(11, 24, 'RN', 'Rio Grande do Norte', 'Região Nordeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(12, 25, 'PB', 'Paraíba', 'Região Nordeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(13, 26, 'PE', 'Pernambuco', 'Região Nordeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(14, 27, 'AL', 'Alagoas', 'Região Nordeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(15, 28, 'SE', 'Sergipe', 'Região Nordeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(16, 29, 'BA', 'Bahia', 'Região Nordeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(17, 31, 'MG', 'Minas Gerais', 'Região Sudeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(18, 32, 'ES', 'Espírito Santo', 'Região Sudeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(19, 33, 'RJ', 'Rio de Janeiro', 'Região Sudeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(20, 35, 'SP', 'São Paulo', 'Região Sudeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(21, 41, 'PR', 'Paraná', 'Região Sul');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(22, 42, 'SC', 'Santa Catarina', 'Região Sul');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(23, 43, 'RS', 'Rio Grande do Sul', 'Região Sul');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(24, 50, 'MS', 'Mato Grosso do sul', 'Região Centro-Oeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(25, 51, 'MT', 'Mato Grosso', 'Região Centro-Oeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(26, 52, 'GO', 'Goiás', 'Região Centro-Oeste');
INSERT INTO estado (id, codigo, uf, nome, regiao) VALUES(27, 53, 'DF', 'Distrito Federal', 'Região Centro-Oeste');

-- estado_civil

INSERT INTO estado_civil (id, tipo, descricao) VALUES(1, 'SOLTEIRO', 'Quem nunca se casou, ou teve um casamento anulado. Ou seja, todos nascemos solteiros e esse estado civil só será alterado com o casamento.');
INSERT INTO estado_civil (id, tipo, descricao) VALUES(2, 'DIVORCIADO', 'Quem foi casado, mas teve o fim do vínculo jurídico do casamento homologado por escritura pública (divórcio extrajudicial) ou decisão judicial.');
INSERT INTO estado_civil (id, tipo, descricao) VALUES(3, 'CASADO', 'Quem se casou e se mantém casado.');
INSERT INTO estado_civil (id, tipo, descricao) VALUES(4, 'VIUVO', 'É aquele que perdeu a condição de casado em decorrência do falecimento da pessoa com quem se casou.');
INSERT INTO estado_civil (id, tipo, descricao) VALUES(5, 'SEPARADO', 'É um estado civil em extinção, já que não existem mais exigências para a homologação de divórcio, bastando que os cônjuges (aqueles que possuem matrimônio) manifestem o desejo de se divorciar. Contudo, como ele ainda está previsto no Código Civil, devemos');

-- instrucao

INSERT INTO instrucao (id, grau) VALUES(1, 'Fundamental - Incompleto');
INSERT INTO instrucao (id, grau) VALUES(2, 'Fundamental - Completo');
INSERT INTO instrucao (id, grau) VALUES(3, 'Médio - Incompleto');
INSERT INTO instrucao (id, grau) VALUES(4, 'Médio - Completo');
INSERT INTO instrucao (id, grau) VALUES(5, 'Superior - Incompleto');
INSERT INTO instrucao (id, grau) VALUES(6, 'Superior - Completo');
INSERT INTO instrucao (id, grau) VALUES(7, 'Pós-graduação (Lato senso) - Incompleto');
INSERT INTO instrucao (id, grau) VALUES(8, 'Pós-graduação (Lato senso) - Completo');
INSERT INTO instrucao (id, grau) VALUES(9, 'Pós-graduação (Stricto sensu, nível mestrado) - Incompleto');
INSERT INTO instrucao (id, grau) VALUES(10, 'Pós-graduação (Stricto sensu, nível mestrado) - Completo');
INSERT INTO instrucao (id, grau) VALUES(11, 'Pós-graduação (Stricto sensu, nível doutor) - Incompleto');
INSERT INTO instrucao (id, grau) VALUES(12, 'Pós-graduação (Stricto sensu, nível doutor) - Completo');

-- pais

INSERT INTO pais (id, codigo, nome) VALUES(1, '001', 'Anguila');
INSERT INTO pais (id, codigo, nome) VALUES(2, '001', 'Antígua e Barbuda');
INSERT INTO pais (id, codigo, nome) VALUES(3, '001', 'Bahamas');
INSERT INTO pais (id, codigo, nome) VALUES(4, '001', 'Barbados');
INSERT INTO pais (id, codigo, nome) VALUES(5, '001', 'Bermudas');
INSERT INTO pais (id, codigo, nome) VALUES(6, '001', 'Canadá');
INSERT INTO pais (id, codigo, nome) VALUES(7, '001', 'Dominica');
INSERT INTO pais (id, codigo, nome) VALUES(8, '001', 'Estados Unidos');
INSERT INTO pais (id, codigo, nome) VALUES(9, '001', 'Granada');
INSERT INTO pais (id, codigo, nome) VALUES(10, '001', 'Ilhas Caimão');
INSERT INTO pais (id, codigo, nome) VALUES(11, '001', 'Ilhas Marianas do Norte');
INSERT INTO pais (id, codigo, nome) VALUES(12, '001', 'Ilhas Virgens Americanas');
INSERT INTO pais (id, codigo, nome) VALUES(13, '001', 'Ilhas Virgens Britânicas');
INSERT INTO pais (id, codigo, nome) VALUES(14, '001', 'Jamaica');
INSERT INTO pais (id, codigo, nome) VALUES(15, '001', 'Montserrat');
INSERT INTO pais (id, codigo, nome) VALUES(16, '001', 'Porto Rico');
INSERT INTO pais (id, codigo, nome) VALUES(17, '001', 'República Dominicana');
INSERT INTO pais (id, codigo, nome) VALUES(18, '001', 'Samoa Americana');
INSERT INTO pais (id, codigo, nome) VALUES(19, '001', 'Santa Lúcia');
INSERT INTO pais (id, codigo, nome) VALUES(20, '001', 'São Cristóvão e Neves');
INSERT INTO pais (id, codigo, nome) VALUES(21, '001', 'São Vicente e Granadinas');
INSERT INTO pais (id, codigo, nome) VALUES(22, '001', 'Trinidad e Tobago');
INSERT INTO pais (id, codigo, nome) VALUES(23, '001', 'Turcas e Caicos');
INSERT INTO pais (id, codigo, nome) VALUES(24, '007', 'Casaquistão');
INSERT INTO pais (id, codigo, nome) VALUES(25, '007', 'Rússia');
INSERT INTO pais (id, codigo, nome) VALUES(26, '020', 'Egito');
INSERT INTO pais (id, codigo, nome) VALUES(27, '027', 'África do Sul');
INSERT INTO pais (id, codigo, nome) VALUES(28, '030', 'Grécia');
INSERT INTO pais (id, codigo, nome) VALUES(29, '031', 'Holanda');
INSERT INTO pais (id, codigo, nome) VALUES(30, '032', 'Bélgica');
INSERT INTO pais (id, codigo, nome) VALUES(31, '033', 'França');
INSERT INTO pais (id, codigo, nome) VALUES(32, '034', 'Espanha');
INSERT INTO pais (id, codigo, nome) VALUES(33, '036', 'Hungria');
INSERT INTO pais (id, codigo, nome) VALUES(34, '039', 'Itália');
INSERT INTO pais (id, codigo, nome) VALUES(35, '040', 'Romênia');
INSERT INTO pais (id, codigo, nome) VALUES(36, '041', 'Suíça');
INSERT INTO pais (id, codigo, nome) VALUES(37, '043', 'Áustria');
INSERT INTO pais (id, codigo, nome) VALUES(38, '044', 'Reino Unido');
INSERT INTO pais (id, codigo, nome) VALUES(39, '045', 'Dinamarca');
INSERT INTO pais (id, codigo, nome) VALUES(40, '046', 'Suécia');
INSERT INTO pais (id, codigo, nome) VALUES(41, '047', 'Noruega');
INSERT INTO pais (id, codigo, nome) VALUES(42, '048', 'Polônia');
INSERT INTO pais (id, codigo, nome) VALUES(43, '049', 'Alemanha');
INSERT INTO pais (id, codigo, nome) VALUES(44, '051', 'Peru');
INSERT INTO pais (id, codigo, nome) VALUES(45, '052', 'México');
INSERT INTO pais (id, codigo, nome) VALUES(46, '053', 'Cuba');
INSERT INTO pais (id, codigo, nome) VALUES(47, '054', 'Argentina');
INSERT INTO pais (id, codigo, nome) VALUES(48, '055', 'Brasil');
INSERT INTO pais (id, codigo, nome) VALUES(49, '056', 'Chile');
INSERT INTO pais (id, codigo, nome) VALUES(50, '057', 'Colômbia');
INSERT INTO pais (id, codigo, nome) VALUES(51, '058', 'Venezuela');
INSERT INTO pais (id, codigo, nome) VALUES(52, '060', 'Malásia');
INSERT INTO pais (id, codigo, nome) VALUES(53, '061', 'Austrália');
INSERT INTO pais (id, codigo, nome) VALUES(54, '062', 'Indonésia');
INSERT INTO pais (id, codigo, nome) VALUES(55, '063', 'Filipinas');
INSERT INTO pais (id, codigo, nome) VALUES(56, '064', 'Nova Zelândia');
INSERT INTO pais (id, codigo, nome) VALUES(57, '065', 'Cingapura');
INSERT INTO pais (id, codigo, nome) VALUES(58, '066', 'Tailândia');
INSERT INTO pais (id, codigo, nome) VALUES(59, '081', 'Japão');
INSERT INTO pais (id, codigo, nome) VALUES(60, '082', 'Coréia do Sul');
INSERT INTO pais (id, codigo, nome) VALUES(61, '084', 'Vietnã');
INSERT INTO pais (id, codigo, nome) VALUES(62, '086', 'China');
INSERT INTO pais (id, codigo, nome) VALUES(63, '090', 'Turquia');
INSERT INTO pais (id, codigo, nome) VALUES(64, '091', 'Índia');
INSERT INTO pais (id, codigo, nome) VALUES(65, '092', 'Paquistão');
INSERT INTO pais (id, codigo, nome) VALUES(66, '093', 'Afeganistão');
INSERT INTO pais (id, codigo, nome) VALUES(67, '094', 'Sri Lanka');
INSERT INTO pais (id, codigo, nome) VALUES(68, '095', 'Myanmar');
INSERT INTO pais (id, codigo, nome) VALUES(69, '098', 'Irã');
INSERT INTO pais (id, codigo, nome) VALUES(70, '212', 'Marrocos');
INSERT INTO pais (id, codigo, nome) VALUES(71, '212', 'Saara Ocidental');
INSERT INTO pais (id, codigo, nome) VALUES(72, '213', 'Argélia');
INSERT INTO pais (id, codigo, nome) VALUES(73, '216', 'Tunísia');
INSERT INTO pais (id, codigo, nome) VALUES(74, '218', 'Líbia');
INSERT INTO pais (id, codigo, nome) VALUES(75, '220', 'Gâmbia');
INSERT INTO pais (id, codigo, nome) VALUES(76, '221', 'Senegal');
INSERT INTO pais (id, codigo, nome) VALUES(77, '222', 'Mauritânia');
INSERT INTO pais (id, codigo, nome) VALUES(78, '223', 'Mali');
INSERT INTO pais (id, codigo, nome) VALUES(79, '224', 'Guiné');
INSERT INTO pais (id, codigo, nome) VALUES(80, '225', 'Costa do Marfim');
INSERT INTO pais (id, codigo, nome) VALUES(81, '226', 'Burkina Faso');
INSERT INTO pais (id, codigo, nome) VALUES(82, '227', 'Níger');
INSERT INTO pais (id, codigo, nome) VALUES(83, '228', 'Togo');
INSERT INTO pais (id, codigo, nome) VALUES(84, '229', 'Benim');
INSERT INTO pais (id, codigo, nome) VALUES(85, '230', 'Maurício');
INSERT INTO pais (id, codigo, nome) VALUES(86, '231', 'Libéria');
INSERT INTO pais (id, codigo, nome) VALUES(87, '232', 'Serra Leoa');
INSERT INTO pais (id, codigo, nome) VALUES(88, '233', 'Gana');
INSERT INTO pais (id, codigo, nome) VALUES(89, '234', 'Nigéria');
INSERT INTO pais (id, codigo, nome) VALUES(90, '235', 'Chade');
INSERT INTO pais (id, codigo, nome) VALUES(91, '236', 'República Centro-Africana');
INSERT INTO pais (id, codigo, nome) VALUES(92, '237', 'Camarões');
INSERT INTO pais (id, codigo, nome) VALUES(93, '238', 'Cabo Verde');
INSERT INTO pais (id, codigo, nome) VALUES(94, '239', 'São Tomé e Príncipe');
INSERT INTO pais (id, codigo, nome) VALUES(95, '240', 'Guiné Equatorial');
INSERT INTO pais (id, codigo, nome) VALUES(96, '241', 'Gabão');
INSERT INTO pais (id, codigo, nome) VALUES(97, '242', 'Congo-Brazzaville');
INSERT INTO pais (id, codigo, nome) VALUES(98, '243', 'Congo-Kinshasa');
INSERT INTO pais (id, codigo, nome) VALUES(99, '244', 'Angola');
INSERT INTO pais (id, codigo, nome) VALUES(100, '245', 'Guiné-Bissau');
INSERT INTO pais (id, codigo, nome) VALUES(101, '246', 'Território Britânico do Oceano Índico');
INSERT INTO pais (id, codigo, nome) VALUES(102, '247', 'Ascensão');
INSERT INTO pais (id, codigo, nome) VALUES(103, '248', 'Seicheles');
INSERT INTO pais (id, codigo, nome) VALUES(104, '249', 'Sudão');
INSERT INTO pais (id, codigo, nome) VALUES(105, '250', 'Ruanda');
INSERT INTO pais (id, codigo, nome) VALUES(106, '251', 'Etiópia');
INSERT INTO pais (id, codigo, nome) VALUES(107, '252', 'Somália');
INSERT INTO pais (id, codigo, nome) VALUES(108, '253', 'Djibuti');
INSERT INTO pais (id, codigo, nome) VALUES(109, '254', 'Quênia');
INSERT INTO pais (id, codigo, nome) VALUES(110, '255', 'Tanzânia');
INSERT INTO pais (id, codigo, nome) VALUES(111, '256', 'Uganda');
INSERT INTO pais (id, codigo, nome) VALUES(112, '257', 'Burundi');
INSERT INTO pais (id, codigo, nome) VALUES(113, '258', 'Moçambique');
INSERT INTO pais (id, codigo, nome) VALUES(114, '260', 'Zâmbia');
INSERT INTO pais (id, codigo, nome) VALUES(115, '261', 'Madagascar');
INSERT INTO pais (id, codigo, nome) VALUES(116, '262', 'Reunião');
INSERT INTO pais (id, codigo, nome) VALUES(117, '263', 'Zimbábue');
INSERT INTO pais (id, codigo, nome) VALUES(118, '264', 'Namíbia');
INSERT INTO pais (id, codigo, nome) VALUES(119, '265', 'Malawi');
INSERT INTO pais (id, codigo, nome) VALUES(120, '266', 'Lesoto');
INSERT INTO pais (id, codigo, nome) VALUES(121, '267', 'Botsuana');
INSERT INTO pais (id, codigo, nome) VALUES(122, '268', 'Suazilândia');
INSERT INTO pais (id, codigo, nome) VALUES(123, '269', 'Comores');
INSERT INTO pais (id, codigo, nome) VALUES(124, '269', 'Mayotte');
INSERT INTO pais (id, codigo, nome) VALUES(125, '290', 'Santa Helena');
INSERT INTO pais (id, codigo, nome) VALUES(126, '291', 'Eritréia');
INSERT INTO pais (id, codigo, nome) VALUES(127, '297', 'Aruba');
INSERT INTO pais (id, codigo, nome) VALUES(128, '298', 'Ilhas Faroé');
INSERT INTO pais (id, codigo, nome) VALUES(129, '299', 'Groenlândia');
INSERT INTO pais (id, codigo, nome) VALUES(130, '350', 'Gibraltar');
INSERT INTO pais (id, codigo, nome) VALUES(131, '351', 'Portugal');
INSERT INTO pais (id, codigo, nome) VALUES(132, '352', 'Luxemburgo');
INSERT INTO pais (id, codigo, nome) VALUES(133, '353', 'Irlanda');
INSERT INTO pais (id, codigo, nome) VALUES(134, '354', 'Islândia');
INSERT INTO pais (id, codigo, nome) VALUES(135, '355', 'Albânia');
INSERT INTO pais (id, codigo, nome) VALUES(136, '356', 'Malta');
INSERT INTO pais (id, codigo, nome) VALUES(137, '357', 'Chipre');
INSERT INTO pais (id, codigo, nome) VALUES(138, '358', 'Finlândia');
INSERT INTO pais (id, codigo, nome) VALUES(139, '359', 'Bulgária');
INSERT INTO pais (id, codigo, nome) VALUES(140, '370', 'Lituânia');
INSERT INTO pais (id, codigo, nome) VALUES(141, '371', 'Letônia');
INSERT INTO pais (id, codigo, nome) VALUES(142, '372', 'Estônia');
INSERT INTO pais (id, codigo, nome) VALUES(143, '373', 'Moldávia');
INSERT INTO pais (id, codigo, nome) VALUES(144, '374', 'Armênia');
INSERT INTO pais (id, codigo, nome) VALUES(145, '375', 'Bielorrússia');
INSERT INTO pais (id, codigo, nome) VALUES(146, '376', 'Andorra');
INSERT INTO pais (id, codigo, nome) VALUES(147, '377', 'Mônaco');
INSERT INTO pais (id, codigo, nome) VALUES(148, '378', 'São Marinho');
INSERT INTO pais (id, codigo, nome) VALUES(149, '379', 'Vaticano');
INSERT INTO pais (id, codigo, nome) VALUES(150, '380', 'Ucrânia');
INSERT INTO pais (id, codigo, nome) VALUES(151, '381', 'Sérvia e Montenegro');
INSERT INTO pais (id, codigo, nome) VALUES(152, '385', 'Croácia');
INSERT INTO pais (id, codigo, nome) VALUES(153, '386', 'Eslovénia');
INSERT INTO pais (id, codigo, nome) VALUES(154, '387', 'Bósnia e Herzegovina');
INSERT INTO pais (id, codigo, nome) VALUES(155, '389', 'Macedônia');
INSERT INTO pais (id, codigo, nome) VALUES(156, '420', 'República Tcheca');
INSERT INTO pais (id, codigo, nome) VALUES(157, '421', 'Eslováquia');
INSERT INTO pais (id, codigo, nome) VALUES(158, '423', 'Liechtenstein');
INSERT INTO pais (id, codigo, nome) VALUES(159, '473', 'Grenada');
INSERT INTO pais (id, codigo, nome) VALUES(160, '500', 'Ilhas Malvinas');
INSERT INTO pais (id, codigo, nome) VALUES(161, '501', 'Belize');
INSERT INTO pais (id, codigo, nome) VALUES(162, '502', 'Guatemala');
INSERT INTO pais (id, codigo, nome) VALUES(163, '503', 'El Salvador');
INSERT INTO pais (id, codigo, nome) VALUES(164, '504', 'Honduras');
INSERT INTO pais (id, codigo, nome) VALUES(165, '505', 'Nicarágua');
INSERT INTO pais (id, codigo, nome) VALUES(166, '506', 'Costa Rica');
INSERT INTO pais (id, codigo, nome) VALUES(167, '507', 'Panamá');
INSERT INTO pais (id, codigo, nome) VALUES(168, '508', 'São Pedro e Miquelon');
INSERT INTO pais (id, codigo, nome) VALUES(169, '509', 'Haiti');
INSERT INTO pais (id, codigo, nome) VALUES(170, '590', 'Guadalupe');
INSERT INTO pais (id, codigo, nome) VALUES(171, '590', 'Saint-Martin (French West Indies)');
INSERT INTO pais (id, codigo, nome) VALUES(172, '591', 'Bolívia');
INSERT INTO pais (id, codigo, nome) VALUES(173, '592', 'Guiana');
INSERT INTO pais (id, codigo, nome) VALUES(174, '593', 'Equador');
INSERT INTO pais (id, codigo, nome) VALUES(175, '594', 'Guiana Francesa');
INSERT INTO pais (id, codigo, nome) VALUES(176, '595', 'Paraguai');
INSERT INTO pais (id, codigo, nome) VALUES(177, '596', 'Martinica');
INSERT INTO pais (id, codigo, nome) VALUES(178, '597', 'Suriname');
INSERT INTO pais (id, codigo, nome) VALUES(179, '598', 'Uruguai');
INSERT INTO pais (id, codigo, nome) VALUES(180, '599', 'Sint Maarten (Antilhas Holandesas)');
INSERT INTO pais (id, codigo, nome) VALUES(181, '670', 'Timor-Leste');
INSERT INTO pais (id, codigo, nome) VALUES(182, '671', 'Guam');
INSERT INTO pais (id, codigo, nome) VALUES(183, '672', 'Territórios Externos Australianos');
INSERT INTO pais (id, codigo, nome) VALUES(184, '673', 'Brunei');
INSERT INTO pais (id, codigo, nome) VALUES(185, '674', 'Nauru');
INSERT INTO pais (id, codigo, nome) VALUES(186, '675', 'Papua-Nova Guiné');
INSERT INTO pais (id, codigo, nome) VALUES(187, '676', 'Tonga');
INSERT INTO pais (id, codigo, nome) VALUES(188, '677', 'Ilhas Salomão');
INSERT INTO pais (id, codigo, nome) VALUES(189, '678', 'Vanuatu');
INSERT INTO pais (id, codigo, nome) VALUES(190, '679', 'Fiji');
INSERT INTO pais (id, codigo, nome) VALUES(191, '680', 'Palau');
INSERT INTO pais (id, codigo, nome) VALUES(192, '681', 'Wallis e Futuna');
INSERT INTO pais (id, codigo, nome) VALUES(193, '682', 'Ilhas Cook');
INSERT INTO pais (id, codigo, nome) VALUES(194, '683', 'Ilha Niue');
INSERT INTO pais (id, codigo, nome) VALUES(195, '685', 'Samoa');
INSERT INTO pais (id, codigo, nome) VALUES(196, '686', 'Kiribati');
INSERT INTO pais (id, codigo, nome) VALUES(197, '687', 'Nova Caledônia');
INSERT INTO pais (id, codigo, nome) VALUES(198, '688', 'Tuvalu');
INSERT INTO pais (id, codigo, nome) VALUES(199, '689', 'Polinésia Francesa');
INSERT INTO pais (id, codigo, nome) VALUES(200, '690', 'Tokelau');
INSERT INTO pais (id, codigo, nome) VALUES(201, '691', 'Micronésia');
INSERT INTO pais (id, codigo, nome) VALUES(202, '692', 'Ilhas Marshall');
INSERT INTO pais (id, codigo, nome) VALUES(203, '850', 'Coréia do Norte');
INSERT INTO pais (id, codigo, nome) VALUES(204, '852', 'Hong Kong');
INSERT INTO pais (id, codigo, nome) VALUES(205, '853', 'Macau');
INSERT INTO pais (id, codigo, nome) VALUES(206, '855', 'Camboja');
INSERT INTO pais (id, codigo, nome) VALUES(207, '856', 'Laos');
INSERT INTO pais (id, codigo, nome) VALUES(208, '880', 'Bangladesh');
INSERT INTO pais (id, codigo, nome) VALUES(209, '886', 'Taiwan');
INSERT INTO pais (id, codigo, nome) VALUES(210, '960', 'Ilhas Maldivas');
INSERT INTO pais (id, codigo, nome) VALUES(211, '961', 'Líbano');
INSERT INTO pais (id, codigo, nome) VALUES(212, '962', 'Jordânia');
INSERT INTO pais (id, codigo, nome) VALUES(213, '963', 'Síria');
INSERT INTO pais (id, codigo, nome) VALUES(214, '964', 'Iraque');
INSERT INTO pais (id, codigo, nome) VALUES(215, '965', 'Kuwait');
INSERT INTO pais (id, codigo, nome) VALUES(216, '966', 'Arábia Saudita');
INSERT INTO pais (id, codigo, nome) VALUES(217, '967', 'Iêmen');
INSERT INTO pais (id, codigo, nome) VALUES(218, '968', 'Omã');
INSERT INTO pais (id, codigo, nome) VALUES(219, '970', 'Palestina');
INSERT INTO pais (id, codigo, nome) VALUES(220, '971', 'Emirados Árabes Unidos');
INSERT INTO pais (id, codigo, nome) VALUES(221, '972', 'Israel');
INSERT INTO pais (id, codigo, nome) VALUES(222, '973', 'Bahrein');
INSERT INTO pais (id, codigo, nome) VALUES(223, '974', 'Qatar');
INSERT INTO pais (id, codigo, nome) VALUES(224, '975', 'Butão');
INSERT INTO pais (id, codigo, nome) VALUES(225, '976', 'Mongólia');
INSERT INTO pais (id, codigo, nome) VALUES(226, '977', 'Nepal');
INSERT INTO pais (id, codigo, nome) VALUES(227, '992', 'Tadjiquistão');
INSERT INTO pais (id, codigo, nome) VALUES(228, '993', 'Turquemenistão');
INSERT INTO pais (id, codigo, nome) VALUES(229, '994', 'Azerbaijão');
INSERT INTO pais (id, codigo, nome) VALUES(230, '995', 'Geórgia');
INSERT INTO pais (id, codigo, nome) VALUES(231, '996', 'Quirguistão');
INSERT INTO pais (id, codigo, nome) VALUES(232, '998', 'Uzbequistão');

-- status_cadastro

INSERT INTO status_cadastro (id, status) VALUES(1, 'PENDENTE');
INSERT INTO status_cadastro (id, status) VALUES(2, 'COMPLETO');
INSERT INTO status_cadastro (id, status) VALUES(3, 'INCOMPLETO');

-- status_evento

INSERT INTO status_evento (id, status) VALUES(1, 'ABERTO');
INSERT INTO status_evento (id, status) VALUES(2, 'ENCERRADO');
INSERT INTO status_evento (id, status) VALUES(3, 'FINALIZADO');
INSERT INTO status_evento (id, status) VALUES(4, 'CONFIRMADO');
INSERT INTO status_evento (id, status) VALUES(5, 'REJEITADO');

-- status_evento_profissional

INSERT INTO status_evento_profissional (id, status) VALUES(1, 'PENDENTE');
INSERT INTO status_evento_profissional (id, status) VALUES(2, 'CONFIRMADO');
INSERT INTO status_evento_profissional (id, status) VALUES(3, 'RECUSADO');

-- status_usuario

INSERT INTO status_usuario (id, status) VALUES(1, 'PENDENTE');
INSERT INTO status_usuario (id, status) VALUES(2, 'ATIVO');
INSERT INTO status_usuario (id, status) VALUES(3, 'INATIVO');
INSERT INTO status_usuario (id, status) VALUES(4, 'CANCELADO');

-- tipo_conta

INSERT INTO tipo_conta (id, codigo, descricao) VALUES(1, '001', 'Conta Corrente de Pessoa Física');
INSERT INTO tipo_conta (id, codigo, descricao) VALUES(2, '002', 'Conta Simples de Pessoa Física');
INSERT INTO tipo_conta (id, codigo, descricao) VALUES(3, '003', 'Conta Corrente de Pessoa Jurídica');
INSERT INTO tipo_conta (id, codigo, descricao) VALUES(4, '006', 'Entidades Públicas');
INSERT INTO tipo_conta (id, codigo, descricao) VALUES(5, '007', 'Depósitos Instituições Financeiras');
INSERT INTO tipo_conta (id, codigo, descricao) VALUES(6, '013', 'Poupança de Pessoa Física');
INSERT INTO tipo_conta (id, codigo, descricao) VALUES(7, '022', 'Poupança de Pessoa Jurídica');
INSERT INTO tipo_conta (id, codigo, descricao) VALUES(8, '023', 'Conta Caixa Fácil');
INSERT INTO tipo_conta (id, codigo, descricao) VALUES(9, '028', 'Poupança de Crédito Imobiliário');
INSERT INTO tipo_conta (id, codigo, descricao) VALUES(10, '032', 'Conta Investimento Pessoa Física');
INSERT INTO tipo_conta (id, codigo, descricao) VALUES(11, '034', 'Conta Investimento Pessoa Jurídica');
INSERT INTO tipo_conta (id, codigo, descricao) VALUES(12, '037', 'Conta Salário');
INSERT INTO tipo_conta (id, codigo, descricao) VALUES(13, '043', 'Depósitos Lotéricos');
INSERT INTO tipo_conta (id, codigo, descricao) VALUES(14, '131', 'Poupança Integrada');

-- tipo_empresa

INSERT INTO tipo_empresa (id, sigla, tipo, descricao) VALUES(1, 'EI', 'Empresário Individual', 'Exerce em nome próprio uma atividade empresarial. Atua individualmente, sem sociedade. Sua responsabilidade é ilimitada (responde com seus bens pessoais pelas obrigações assumidas com a atividade empresarial). O empresário pode exercer atividade industria');
INSERT INTO tipo_empresa (id, sigla, tipo, descricao) VALUES(2, 'MEI', 'Microempreendedor Individual', 'é o empresário individual com receita bruta anual até R$ 81.000,00no ano (1º de janeiro à 31 de dezembro) ou R$ 6.750,00 em média por mês de atuação para o primeiro ano de exercício das atividades, optante pelo Simples Nacional e SIMEI. O Simples Naciona');
INSERT INTO tipo_empresa (id, sigla, tipo, descricao) VALUES(3, 'EIRELI', 'Empresa Individual de Responsabilidade L', 'Atuação individual - sem sócios. Responsabilidade do empresário é limitada ao capital social (valor do investimento, em dinheiro ou bens). Obrigatoriedade de capital social integralizado de no mínimo 100 salários mínimos. A EIRELI possibilita a atuação in');
INSERT INTO tipo_empresa (id, sigla, tipo, descricao) VALUES(4, 'LTDA', 'Sociedade Empresária', 'Neste tipo de empresa é possível a atuação coletiva entre dois ou mais sócios, sendo sua responsabilidade limitada ao capital social. Deverá adotar uma das espécies de sociedade existentes (S/A, Sociedade Limitada - LTDA, etc.). A espécie de sociedade emp');
INSERT INTO tipo_empresa (id, sigla, tipo, descricao) VALUES(5, 'SS', 'Sociedade Simples', 'Pessoa Jurídica com atuação Coletiva, ou seja, 02 (dois) ou mais sócios. A responsabilidade dos sócios é ilimitada. Porém, poderá adotar a espécie societária de Sociedade Limitada - Sociedade Simples Ltda., passando a responsabilidade dos sócios a ser lim');
INSERT INTO tipo_empresa (id, sigla, tipo, descricao) VALUES(6, 'SLU', 'Sociedade Limitada Unipessoal', 'Pelo advento da Lei nº 13.874, de 20 de Setembro de 2019 (Lei da Liberdade Econômica), a Sociedade Limitada, que até então somente poderia ser constituída na forma pluripessoal (duas ou mais pessoas), passou a ser admitida na forma unipessoal – § 1º e 2º ');
INSERT INTO tipo_empresa (id, sigla, tipo, descricao) VALUES(7, 'SA', 'Sociedade Anônima', 'Na empresa de Sociedade Anônima também existe mais de um sócio empresário. Nesse caso, eles são chamados de acionistas, isso porque o capital da empresa é distribuído em ações. A empresa de Sociedade Anônima pode ser de dois tipo: de capital aberto e de ');
INSERT INTO tipo_empresa (id, sigla, tipo, descricao) VALUES(8, 'ME', 'Microempresa', 'As Microempresas são entendidas assim a partir do seu faturamento bruto anual que não pode ultrapassar os 360 mil reais. Segundo o que estabelece a lei complementar 123/2016, a Microempresa pode ser optante pelo Simples Nacional. Este é um regime de paga');
INSERT INTO tipo_empresa (id, sigla, tipo, descricao) VALUES(9, 'EPP', 'Empresa de Pequeno Porte', 'Para ser uma Empresa de Pequeno Porte é necessário que ela fatura anualmente entre R$ 360 mil e até R$ 3,6 milhões. Esse tipo de empresa também pode ser optante pelo Simples Nacional.');
INSERT INTO tipo_empresa (id, sigla, tipo, descricao) VALUES(10, 'SFL', 'Sem fins lucrativos', 'Os negócios sem fins lucrativos também são pessoas jurídicas. Esses possuem características bem distintas das demais empresas. A principal característica e que se destaca é que eles não visam o lucro ao praticarem suas atividades. Apesar disso, entra rec');
INSERT INTO tipo_empresa (id, sigla, tipo, descricao) VALUES(11, 'SCA', 'Sociedade em Comandita por Ações', 'A Sociedade em Comandita por Ações pode assemelhar-se às Sociedades Anônimas, isso porque o capital é dividido em ações. E existem dois tipos de sócios: os comanditados e os comanditários. É uma sociedade híbrida regida pelas normas das Sociedades Anônim');
INSERT INTO tipo_empresa (id, sigla, tipo, descricao) VALUES(12, 'SCS', 'Sociedade em Comandita Simples', 'A Sociedade em Comandita Simples assemelha-se a anterior. No caso específico, esse tipo de empresa também é constituída por dois sócios, que são: – os comanditários. Estes têm responsabilidade apenas sobre suas cotas; – os comanditados. Estes são pessoa');

-- transporte

INSERT INTO transporte (id, tipo) VALUES(1, 'NAO POSSUO TRANSPORTE');
INSERT INTO transporte (id, tipo) VALUES(2, 'CARRO');
INSERT INTO transporte (id, tipo) VALUES(3, 'MOTO');
INSERT INTO transporte (id, tipo) VALUES(4, 'ONIBUS');
INSERT INTO transporte (id, tipo) VALUES(5, 'UBER');
INSERT INTO transporte (id, tipo) VALUES(6, 'TAXI');
INSERT INTO transporte (id, tipo) VALUES(7, 'BICICLETA');
INSERT INTO transporte (id, tipo) VALUES(8, 'CHARRETE');
INSERT INTO transporte (id, tipo) VALUES(9, 'BARCO');
INSERT INTO transporte (id, tipo) VALUES(10, 'OUTRO');